### ISSUE TITLE
Edit user fail: academicDicipline2 too long

### ISSUE THREAD

**Issue by NajibAbuSamra** [shalomweiss/mm-system-2017#63] opened 2017-11-06 17:41 UTC
![image](https://user-images.githubusercontent.com/28620326/32455253-5b8dfa5e-c32a-11e7-8279-9a114e4e1e2f.png)

This is happening from the web, the second academic discipline is empty in the db

**Comment by danielzar2710** [comment] 2017-11-06 18:07
![screenshot_2](https://user-images.githubusercontent.com/26320595/32456381-0bb768fe-c32e-11e7-959b-85fe91d728d3.png)
as you can see the academic institues im am sending are fine

**Comment by danielzar2710** [comment] 2017-11-06 18:08
the problem is that im sending wrong city id, when i do not have any city list

**Comment by danielzar2710** [comment] 2017-11-07 12:14
I understood this is not a problem of the web, and I indeed got spaces with my data, this can be supported by looking at simillar rows and seeing that they lack tis problem. To conclude I do not remove this issue but i think it's preety much closed
@NajibAbuSamra

**Comment by NajibAbuSamra** [comment] 2017-11-07 21:08
is it working now? @danielzar2710

**Comment by danielzar2710** [comment] 2017-11-08 07:19
I think it is a problm with the old mentees, something there went wrong, i do not know what or why, but now it is ok, may i suggest to delete all the users and pairs and start again. I have an idea we will call deleting all users as protocol: "great flood".

**Comment by danielzar2710** [comment] 2017-11-08 07:20
![image](https://user-images.githubusercontent.com/26320595/32536185-f55bd728-c465-11e7-847a-4b0a6a3a87e7.png)
here you see that the decipline i send you is fine

**Comment by danielzar2710** [comment] 2017-11-08 07:38
I checked with the "new user" and it is working so I'm closing this

**Closed as completed** 2017-11-08 07:38 UTC
Labels: bug
